<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="en_US" sourcelanguage="en_US">
<!--
  English (source) skeleton translation file for LvkSpriteEditor.
  Generated by Phase 6b (Item 27).  Populate with `lupdate src/ -ts
  translations/lvkspriteeditor_en.ts` once tr() coverage exists in the GUI.
-->
<context>
</context>
</TS>
