<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="fr_FR" sourcelanguage="en_US">
<!--
  French (fr_FR) skeleton translation file for LvkSpriteEditor.
  Generated by Phase 6b (Item 27).  Populate via `lupdate src/ -ts
  translations/lvkspriteeditor_fr.ts`.
-->
<context>
</context>
</TS>
