<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="es_ES" sourcelanguage="en_US">
<!--
  Spanish (es_ES) skeleton translation file for LvkSpriteEditor.
  Generated by Phase 6b (Item 27).  Populate via `lupdate src/ -ts
  translations/lvkspriteeditor_es.ts`.
-->
<context>
</context>
</TS>
